# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Carto54
                                 A QGIS plugin
 This plugins is used to add more customization to the Carto54 Web app
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-30
        copyright            : (C) 2020 by Conseil Départemental de Meurthe-et-Moselle
        email                : hvitoux@departement54.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Carto54 class from file Carto54.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .carto54 import Carto54
    return Carto54(iface)
